
k_SHADER_LANDSCAPE <- 0
k_SHADER_LANDSCAPE_ND <- 1
k_SHADER_MODEL <- 2
k_SHADER_MODEL_ND <- 3
k_SHADER_GRASS <- 4
k_SHADER_GRASS_ND <- 5
k_SHADER_OCEAN <- 6
k_SHADER_DECAL <- 7
k_SHADER_PARTICLE <- 8
k_SHADER_PARTICLE_ND <- 9
k_SHADER_SKYBOX <- 10
k_SHADER_LANDSCAPE_EDGES <- 11
k_SHADER_SCREEN_PLANE <- 12
k_SHADER_SCREEN_PLANE_BLOOM_EXTRACT <- 13
k_SHADER_SCREEN_PLANE_BLOOM_COMBINE <- 14
k_SHADER_SCREEN_PLANE_BLUR <- 15
k_SHADER_SCREEN_PLANE_EDGE_DETECT <- 16
k_SHADER_SCREEN_PLANE_LANDSCAPE_DETAIL <- 17

k_RENDER_MODE_WORLD_SPACE_SIMPLE <- 0
k_RENDER_MODE_WORLD_SPACE_REFLECTION <- 1
k_RENDER_MODE_WORLD_SPACE_REFRACTION <- 2
k_RENDER_MODE_WORLD_SPACE_SCREEN_NORMAL_MAP <- 3

k_TEXTURE_SLOT_01 <- 0
k_TEXTURE_SLOT_02 <- 1
k_TEXTURE_SLOT_03 <- 2
k_TEXTURE_SLOT_04 <- 3
k_TEXTURE_SLOT_05 <- 4
k_TEXTURE_SLOT_06 <- 5
k_TEXTURE_SLOT_07 <- 6
k_TEXTURE_SLOT_08 <- 7


